/**
 * Display shapes for the Riddlon system chat: the local story catalog, and the example packages
 * the app ships for install.
 *
 * Every catalog row is built from the real registry (`storyRuntime.installedPackages`). The
 * decorative "also installed" stories that used to live here were pure mockup content and made a
 * freshly reset library look populated — docs/arc42 §5.3's registry is the only source now.
 */

export type StoryStatus = 'running' | 'notStarted' | 'solved' | 'unknown';

export interface CatalogEntry {
	id: string;
	title: string;
	status: StoryStatus;
	contactCount: number;
	/** The package's own `manifest.tags` (#53). The card used to print a hardcoded "Krimi" for
	 *  every installed story, which was the demo story's genre asserted about everything. */
	tags: string[];
	/** Only set for the active session — the only package whose progress is loaded. */
	chapter?: { current: number; total: number };
	progressPercent?: number;
}

/**
 * One entry of `static/stories/index.json`, generated by `scripts/build-stories.mjs --static`
 * from the packages under `stories/`. The app installs these through the ordinary URL importer,
 * so a bundled example takes exactly the same path as a package a player fetches themselves.
 */
export interface BundledStory {
	slug: string;
	id: string;
	title: string;
	version: string;
	zip: string;
	bytes: number;
	sha256: string;
	fileCount: number;
}

/**
 * Story packages are kilobytes of JSON, not gigabytes of model weights, so they need their own
 * size label — `llm/catalog.ts`'s `formatSizeLabel` starts at MB and rounds an 8 KB package down
 * to "0 MB". German decimal comma, matching the rest of the UI.
 */
export function formatPackageSize(bytes: number): string {
	if (bytes < 1024) return `${Math.max(bytes, 0)} B`;
	const kb = bytes / 1024;
	if (kb < 1000) return `${Math.round(kb)} KB`;
	const mb = kb / 1024;
	if (mb < 1000) return `${mb.toFixed(1).replace('.', ',')} MB`;
	return `${(mb / 1024).toFixed(1).replace('.', ',')} GB`;
}

/** Defensive: the index is generated, but a stale service-worker cache could serve anything. */
export function parseBundledStories(value: unknown): BundledStory[] {
	if (!Array.isArray(value)) return [];
	return value.filter((entry): entry is BundledStory => {
		if (typeof entry !== 'object' || entry === null) return false;
		const row = entry as Record<string, unknown>;
		return (
			typeof row.id === 'string' &&
			typeof row.title === 'string' &&
			typeof row.zip === 'string' &&
			typeof row.version === 'string' &&
			typeof row.bytes === 'number'
		);
	});
}
